#!/bin/bash
#$ -M user@shef.ac.uk
#$ -m bea
#$ -l h_rt=00:02:00
#$ -l rmem=100M
#$ -l gpu=1

# Test if GPU locks are cleared if a job fails.
#
# Here we run a C program that first sleeps for 60s then tries to allocate
# (using calloc) more memory than the scheduler has allocated to this session.
#
# The lock should be created by the prolog script and and visible for 60s then
# should be cleared by the epilog script.
#
# This test is designed to be run on Grid Engine, configured as per README.md
#
./test_sge_gpu_job_fail 10000
